### ISSUE TITLE
Package does not exist when using composer require fraank/view-counter

### ISSUE THREAD

**Issue by James7777** [fraank/ViewCounter#1]
Package does not exist when using composer require fraank/view-counter

Problem for laravel5

**Comment by fraank** [comment]
I'm just testing it with laravel5. I will give support as soon as I got it up and running. Anyway: Thanks for trying!

**Comment by homoky** [comment]
+1

**Comment by fraank** [comment]
I've fixed the issue and did some compatibility stuff to make it work for laravel5. In my case it's now working fine.

**Comment by James7777** [comment]
Thank you, I will try again.
